### ISSUE TITLE
Local download only

### ISSUE THREAD

**Issue by TechnoDezi** [Azure/azure-media-migration#205]
Is it possible to just run the migration tool locally and store the migrated content locally on disc instead of uploading again to a storage account?

**Comment by pohhsu** [comment]
the tool currently doesn't support this scenario.

**Comment by duggaraju** [comment]
Most of the pieces for  local file support are already built in to the code.  But it is not exposed as a command line option  (The plan for -Cloud Azure|Local).  You can chage one line in the code to change the default from Azure to Local and give a local directory as a destination.

**Comment by TechnoDezi** [comment]
Morning, geeat, that is most helpful. Which line,  then i can do it, give it a test,  and maybe submit a change with a cmd option

**Comment by duggaraju** [comment]
Just modify https://github.com/Azure/azure-media-migration/blob/4c647666217b3eb94d9f997adb8c76f963d8ad47/GlobalOptionsBinder.cs#L65C27-L65C32 from CloudType.Azure to CloudType.Local . Can also be made into an option in GlobaOptionsBinder.cs if you want a command line option -c (--cloud-type)
