### ISSUE TITLE
Multi audio streams not migrating correctly

### ISSUE THREAD

**Issue by mouab215** [Azure/azure-media-migration#230]
Whenever I use a video Asset with multi audio streams (e.g. english + french). The output will be in CMAF (as expected) and have the same amount of audio streams but then english + english.

**Comment by pohhsu** [comment]
Hi @mouab215,

Is it possible for you to provide input assets for us investigate?  If not, is it possible to provide the ism/ismc files?

Thanks.

**Comment by mouab215** [comment]
hi @pohhsu, Yes, here it is. Let me know if it works: 
https://we.tl/t-4NFzYdYOqa

**Comment by duggaraju** [comment]
Looks like we are hitting a bug with shaka packager, where even though in the command line we specify the two audio streams as eng & fre, the generated mpd/m3u8 only has language as eng.

**Comment by duggaraju** [comment]
Create a pull request #231 for this issue. While waiting for the fix, the customer can make the change locally and test.  It is a one line change in Manifest.cs  (or you can use the duggaraju/mulit_audio) branch.

**Comment by mouab215** [comment]
Hey @duggaraju , I've tried it with the latest commit, however i still end up with 2 english audio tracks while the initial asset contains both english and french
